GasStationProject/force-app/main/default/objects/Fuel_details__c/Fuel_details__c.object-meta.xml
<CustomObject>
    <label>Fuel details</label>
    <nameField>
        <displayFormat>fuel-{000}</displayFormat>
        <label>Fuel details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fuel details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GasStationProject/force-app/main/default/objects/Fuel_details__c/fields/Fuel_Supplied__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Supplied__c</fullName>
    <label>Fuel Supplied</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GasStationProject/force-app/main/default/objects/Fuel_details__c/fields/Gas_Station__c.field-meta.xml
<CustomField>
    <fullName>Gas_Station__c</fullName>
    <label>Gas Station</label>
    <referenceTo>Gas_Station__c</referenceTo>
    <relationshipLabel>Fuel details</relationshipLabel>
    <relationshipName>Fuel_details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GasStationProject/force-app/main/default/objects/Gas_Station__c/Gas_Station__c.object-meta.xml
<CustomObject>
    <label>Gas Station</label>
    <nameField>
        <displayFormat>Gas-{000}</displayFormat>
        <label>Gas Station</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gas Stations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

GasStationProject/force-app/main/default/classes/FuelRecordHandler.cls
public class FuelRecordHandler {    

    public static void beforeDeleteInfo(list<Fuel_details__c> fuelList){

        //fuelList = [select Id from Fuel_details__c];

        for(Fuel_details__c ful : fuelList){

            if(ful.Fuel_supplied__c > 500){

                ful.addError('you cannot delete the fuel details record because it is associated with supplier and Gas station records');

            }

        }

    }  

    public static void beforeDeleteGas(list<Gas_Station__c> gasList){

        //fuelList = [select Id from Fuel_details__c];

        for(Gas_Station__c gas : gasList){

            if(gas.Fuel_price_liter__c <= 50){

                gas.addError('enter the fuel price before saving the record, Minimum price should be 50');

            }

        }

    } 

}